defaults:
  - default
  - _self_

optimizer:
  _target_: hyperaudioset.optim.RiemannSGD
  lr: 0.3

lr_scheduler:
  _target_: hyperaudioset.optim.lr_scheduler.BurnInLRScheduler
  burnin_step: 20
  burnin_scale: 0.01
