defaults:
  - system: default
  - data: default
  - model: default
  - optimizer: default
  - criterion: default
  - _self_

epochs: 20
now: ${now:%Y%m%d-%H%M%S}
exp_dir: "./exp/${.now}"
tensorboard_dir: "./tensorboard/${.now}"

hydra:
  job:
    chdir: false
  run:
    dir: "${exp_dir}/log/${now}"
