defaults:
  - system: default
  - data: default
  - model: default
  - optimizer: default
  - criterion: default
  - _self_

# train & visualize
exp_dir: "./exp/${.now}"

# train
epochs: 300
tensorboard_dir: "./tensorboard/${.now}"

# visualize
root: ???
depth: 3

now: ${now:%Y%m%d-%H%M%S}

hydra:
  job:
    chdir: false
  run:
    dir: "${exp_dir}/log/${now}"
