defaults:
  - system: default
  - data: default
  - model: default
  - optimizer: default
  - criterion: default
  - _self_

hydra:
  job:
    chdir: false
  run:
    dir: "./log/${now:%Y%m%d-%H%M%S}"
